use runtime::producer::{
    AgentArchetype, ProducerRun, ProducerStage, ProducerWorkspace, RunStep, RunType, StageStatus,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::thread;
use std::time::Duration;

/// Input for starting a Slate analysis run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlateAnalyzeInput {
    pub workspace_name: String,
    pub slate_file: Option<String>,
    pub cwd: String,
}

/// Result of a Slate analysis run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlateAnalyzeResult {
    pub run_id: String,
    pub status: String,
    pub artifacts: Vec<String>,
    pub message: String,
}

/// Execute a full Slate analysis run for a workspace.
pub fn run_slate_analyze(input: &Value) -> Result<String, String> {
    let input: SlateAnalyzeInput = serde_json::from_value(input.clone()).map_err(|e| e.to_string())?;
    let cwd = PathBuf::from(&input.cwd);
    let ws_root = cwd.join(".nova").join("workspaces").join(&input.workspace_name);

    if !ws_root.exists() {
        return Err(format!("Workspace '{}' does not exist.", input.workspace_name));
    }

    // Load workspace
    let ws_path = ws_root.join("workspace.json");
    let mut ws: ProducerWorkspace = if ws_path.exists() {
        let content = fs::read_to_string(&ws_path).map_err(|e| e.to_string())?;
        serde_json::from_str(&content).map_err(|e| e.to_string())?
    } else {
        ProducerWorkspace::new(&input.workspace_name, cwd.clone())
    };

    // Update stage state to running
    ws.current_stage = ProducerStage::Slate;
    if let Some(s) = ws.stages.get_mut(&ProducerStage::Slate) {
        s.status = StageStatus::Running;
    }
    save_workspace(&ws, &ws_path)?;

    let run_id = format!("slate-run-{}", chrono::Utc::now().format("%Y%m%d-%H%M%S"));
    let mut run = ProducerRun::new(&run_id, RunType::SlateAnalyze);
    run.start();

    let runs_dir = ws_root.join("runs").join(&run_id);
    fs::create_dir_all(&runs_dir).map_err(|e| e.to_string())?;
    fs::create_dir_all(runs_dir.join("steps")).map_err(|e| e.to_string())?;

    // Spawn agents in parallel
    let agents = vec![
        AgentArchetype::ScriptAnalyst,
        AgentArchetype::BudgetOracle,
    ];

    let mut handles = Vec::new();
    for (i, agent) in agents.iter().enumerate() {
        let step_number = (i + 1) as u32;
        let agent_name = agent.display_name().to_string();
        let agent_id = format!("{}-{}", run_id, agent_name.to_lowercase().replace(' ', "-"));
        let runs_dir_clone = runs_dir.clone();
        let ws_name = input.workspace_name.clone();
        let run_id_clone = run_id.clone();

        let mut step = RunStep::new(step_number, agent_id.clone(), agent_name.clone());
        step.start();
        save_step(&step, &runs_dir_clone)?;

        run.add_step(step.clone());

        let handle = thread::spawn(move || {
            // Simulate agent work
            thread::sleep(Duration::from_millis(200));

            let artifact_content = format!(
                "# {} Output for {}\n\nGenerated by {} during {}.\n",
                agent_name, ws_name, agent_id, run_id_clone
            );

            let artifact_path = runs_dir_clone
                .join("steps")
                .join(format!("{:02}-{}.md", step_number, agent_name.to_lowercase().replace(' ', "-")));
            let _ = fs::write(&artifact_path, artifact_content);

            let mut completed_step = step;
            completed_step.complete();
            completed_step.output_summary = Some(format!("{} completed.", agent_name));
            let _ = save_step(&completed_step, &runs_dir_clone);
            completed_step
        });
        handles.push((step_number, handle));
    }

    // Wait for all agents to complete
    for (step_number, handle) in handles {
        let completed_step = handle.join().map_err(|_| format!("agent {step_number} panicked"))?;
        if let Some(s) = run.steps.iter_mut().find(|s| s.step_number == step_number) {
            *s = completed_step;
        }
    }

    // Synthesis step
    let mut synthesizer_step = RunStep::new(
        3,
        format!("{run_id}-synthesizer"),
        "Synthesis Agent",
    );
    synthesizer_step.start();
    save_step(&synthesizer_step, &runs_dir)?;

    // Generate SLATE_REPORT.md
    let slate_report = format!(
        "# Slate Analysis Report\n\n## Workspace: {}\n## Run: {}\n\n## Summary\nAll slate agents completed successfully.\n\n## Next Action\nProceed to `/stage package`.\n",
        ws.name, run_id
    );

    let artifacts_dir = ws_root.join("artifacts");
    fs::create_dir_all(&artifacts_dir).map_err(|e| e.to_string())?;
    let slate_report_path = artifacts_dir.join("SLATE_REPORT.md");
    fs::write(&slate_report_path, slate_report).map_err(|e| e.to_string())?;

    synthesizer_step.complete();
    synthesizer_step.output_summary = Some("Synthesized SLATE_REPORT.md".to_string());
    save_step(&synthesizer_step, &runs_dir)?;
    run.add_step(synthesizer_step);

    // Complete run and unlock next stage
    run.complete();
    run.artifact_names.push("SLATE_REPORT.md".to_string());
    save_run(&run, &runs_dir)?;

    ws.complete_stage(ProducerStage::Slate);
    save_workspace(&ws, &ws_path)?;

    let result = SlateAnalyzeResult {
        run_id: run.run_id.clone(),
        status: "completed".to_string(),
        artifacts: vec!["SLATE_REPORT.md".to_string()],
        message: format!(
            "Slate analysis complete. {} projects evaluated. Package stage is now ready.",
            input.slate_file.as_deref().unwrap_or("slate")
        ),
    };

    serde_json::to_string_pretty(&result).map_err(|e| e.to_string())
}

/// List the steps of a given run.
pub fn run_status(input: &Value) -> Result<String, String> {
    let workspace_name: String = input
        .get("workspace_name")
        .and_then(|v| v.as_str())
        .unwrap_or("default")
        .to_string();
    let run_id: String = input
        .get("run_id")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    let cwd: String = input
        .get("cwd")
        .and_then(|v| v.as_str())
        .unwrap_or(".")
        .to_string();

    if run_id.is_empty() {
        return Ok(serde_json::json!({
            "status": "no_active_run",
            "message": "No active run. Start one with `/run slate analyze --slate <file>`."
        })
        .to_string());
    }

    let run_path = PathBuf::from(&cwd)
        .join(".nova")
        .join("workspaces")
        .join(&workspace_name)
        .join("runs")
        .join(&run_id)
        .join("run.json");

    if !run_path.exists() {
        return Ok(serde_json::json!({
            "status": "not_found",
            "message": format!("Run {run_id} not found.")
        })
        .to_string());
    }

    let content = fs::read_to_string(&run_path).map_err(|e| e.to_string())?;
    let run: ProducerRun = serde_json::from_str(&content).map_err(|e| e.to_string())?;

    let steps: Vec<Value> = run
        .steps
        .iter()
        .map(|s| {
            serde_json::json!({
                "number": s.step_number,
                "agent": s.agent_name,
                "status": format!("{:?}", s.status),
                "icon": s.status.icon(),
            })
        })
        .collect();

    Ok(serde_json::json!({
        "run_id": run.run_id,
        "status": format!("{:?}", run.status),
        "steps": steps,
    })
    .to_string())
}

fn save_workspace(ws: &ProducerWorkspace, path: &Path) -> Result<(), String> {
    let json = serde_json::to_string_pretty(ws).map_err(|e| e.to_string())?;
    fs::write(path, json).map_err(|e| e.to_string())
}

fn save_run(run: &ProducerRun, runs_dir: &Path) -> Result<(), String> {
    let path = runs_dir.join("run.json");
    let json = serde_json::to_string_pretty(run).map_err(|e| e.to_string())?;
    fs::write(path, json).map_err(|e| e.to_string())
}

fn save_step(step: &RunStep, runs_dir: &Path) -> Result<(), String> {
    let path = runs_dir
        .join("steps")
        .join(format!("{:02}-{}.json", step.step_number, step.agent_name.to_lowercase().replace(' ', "-")));
    let json = serde_json::to_string_pretty(step).map_err(|e| e.to_string())?;
    fs::write(path, json).map_err(|e| e.to_string())
}
